In [1]:
# conda
# pip
!conda install pytorch torchvision torchaudio -c pytorch

Solving environment: | ^C
failed with initial frozen solve. Retrying with flexible solve.

CondaError: KeyboardInterrupt



In [3]:
!conda install matplotlib

Solving environment: | ^C
failed with initial frozen solve. Retrying with flexible solve.

CondaError: KeyboardInterrupt



In [6]:
import torch

In [ ]:
# Math description of tensors and matrices
# Tensor: more than 2 dimensions
# Matrix: 2 dimensions

# Pytorch description
# Tensor: is a data object that holds numbers

In [29]:
x = torch.randn(5, 5)

In [30]:
x

tensor([[-1.3320,  0.2861, -0.0522,  0.3986,  1.0490],
        [ 0.1966,  1.1549,  0.1714,  0.3404, -0.5106],
        [-0.0229,  0.3813, -0.4345,  0.5519, -0.0225],
        [ 0.2048,  0.2417, -0.9606, -0.6502,  0.0591],
        [-0.2170,  0.5070, -0.3575, -1.2855,  0.4434]])

In [31]:
x = x + 1

In [32]:
x

tensor([[-0.3320,  1.2861,  0.9478,  1.3986,  2.0490],
        [ 1.1966,  2.1549,  1.1714,  1.3404,  0.4894],
        [ 0.9771,  1.3813,  0.5655,  1.5519,  0.9775],
        [ 1.2048,  1.2417,  0.0394,  0.3498,  1.0591],
        [ 0.7830,  1.5070,  0.6425, -0.2855,  1.4434]])

In [33]:
x = x * 3

In [34]:
x

tensor([[-0.9960,  3.8584,  2.8435,  4.1959,  6.1471],
        [ 3.5897,  6.4647,  3.5141,  4.0213,  1.4681],
        [ 2.9312,  4.1440,  1.6966,  4.6557,  2.9324],
        [ 3.6144,  3.7252,  0.1182,  1.0493,  3.1773],
        [ 2.3490,  4.5211,  1.9276, -0.8565,  4.3302]])

# Image classification
# Image generation/synthesis
# Object Detection
# Image segmentation

# Natural Language Processing

# Text Classification

# Text Generation

# Regression

In [ ]:
# 3Blue1Brown - 5 videos on neural networks

In [ ]:
# Dataset Class
# Data Loader (data, label)
# Model (neural network)
# Main Training Loop
# Visualization/Statistics of the Performance

In [14]:
import torch
import torch.nn as nn
import torch.optim as optim

In [12]:
class ExampleNetwork(nn.Module):
    def __init__(self):
        super(ExampleNetwork, self).__init__()
        
        self.layer1 = nn.Linear(5, 10)
        self.layer2 = nn.Linear(10, 20)
        self.layer3 = nn.Linear(20, 10)
        self.layer4 = nn.Linear(10, 5)
        self.layer5 = nn.Linear(5, 1)
        
        self.act = nn.ReLU()
    
    def forward(self, x):
        x = self.act(self.layer1(x))
        x = self.act(self.layer2(x))
        x = self.act(self.layer3(x))
        x = self.act(self.layer4(x))
        x = self.act(self.layer5(x))
        
        return x

In [3]:
model = ExampleNetwork()

In [20]:
x.shape

torch.Size([5])

In [30]:
model(x)

tensor([-0.0035,  0.1664,  0.1644, -0.0986,  0.0210], grad_fn=<AddBackward0>)

In [35]:
device = ('cuda' if torch.cuda.is_available() else 'cpu')

In [36]:
x = torch.randn(5, 5)

In [ ]:
x = x.to(device)

In [34]:
# hyperparameters
num_epochs = 100
batch_size = 10

model = ExampleNetwork().to(device)

loss_fx = nn.MSELoss().to(device)
optimizer = optim.Adam(model.parameters())

for epoch in range(num_epochs):
    for batch in dataloader:
        features, labels = batch.to(device)
        
        output = model(features)
        loss = loss_fx(output, labels)
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
    # Train
    pass


In [16]:
output = model(data)
loss = loss_fx(output, labels)
print(loss)

tensor(0.8998, grad_fn=<MseLossBackward>)


In [20]:
from torch.utils.data import Dataset, DataLoader

In [29]:
class ExampleDataset(Dataset):
    def __init__(self, num_features=5):
        self.data = torch.randn(1000, num_features)
        self.labels = torch.randn(1000, 1)
    
    def __len__(self):
        return len(self.data)
    
    def __getitem__(self, index):
        return self.data[index], self.labels[index]

In [30]:
dataset = ExampleDataset()

In [31]:
len(dataset)

1000

In [32]:
dataloader = DataLoader(dataset, batch_size=10, shuffle=True, num_workers=0)

In [33]:
next(iter(dataloader))

[tensor([[-0.0593,  0.2754,  1.9307, -1.6774, -1.7609],
         [ 1.3319, -0.6838,  1.0871, -0.8224,  0.2338],
         [-1.6990, -0.3557,  0.9651, -0.1530, -1.9045],
         [-0.3813, -1.0759, -2.1031, -0.8404,  0.6683],
         [ 1.6061, -0.5187, -2.9920,  0.5348, -0.1227],
         [ 1.0023,  0.1456, -0.0541,  1.3076, -0.3491],
         [-0.6739, -0.2806, -0.3158, -0.4833,  0.0086],
         [ 0.8036,  2.1257,  1.1129, -0.2406,  0.0373],
         [-0.9306, -0.7897,  0.3731,  0.1188,  0.7869],
         [-0.9581, -0.9095,  2.1855,  0.2636, -0.7450]]),
 tensor([[ 1.6488],
         [-1.7388],
         [ 0.8124],
         [ 1.8182],
         [ 1.5306],
         [-0.1193],
         [-1.6087],
         [-0.0130],
         [ 0.3827],
         [ 0.9617]])]